//! Semantic events produced by a [`crate::Session`].

use crate::state::{ModeChange, ModeListEntry, WhoisInfo};
use schwaetz_proto::{Message, Source, Tags};

/// An event with its context.
#[derive(Clone, Debug, PartialEq)]
pub struct SessionEvent {
    /// Unix milliseconds: IRCv3 `server-time` if present, otherwise the local receive time.
    pub time: i64,
    /// Set when the event answers a command sent with [`crate::Session::send_labeled`].
    pub label: Option<String>,
    pub kind: Event,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ChatKind {
    Privmsg,
    Notice,
    /// CTCP ACTION (`/me`).
    Action,
    /// Tags-only message (typing notifications, reactions).
    Tagmsg,
}

/// Where a message belongs.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Target {
    /// A channel; `status` is a STATUSMSG prefix like `@` for `@#chan`.
    Channel { name: String, status: Option<char> },
    /// A private conversation with `peer` (the other party, also for our own echoed messages).
    Query { peer: String },
    /// Server notices and messages to `*` / `$mask` targets.
    Server,
}

impl Target {
    pub fn name(&self) -> Option<&str> {
        match self {
            Target::Channel { name, .. } => Some(name),
            Target::Query { peer } => Some(peer),
            Target::Server => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct Chat {
    pub kind: ChatKind,
    pub from: Source,
    pub target: Target,
    /// Raw text including formatting codes; multiline messages contain `\n`.
    pub text: String,
    pub tags: Tags,
    pub msgid: Option<String>,
    /// Sent by us (echo-message, self-message, local echo or history).
    pub own: bool,
    /// Part of a history/playback batch rather than live traffic.
    pub history: bool,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum StandardReplyKind {
    Fail,
    Warn,
    Note,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum TwitchEvent {
    /// Timeout/ban (`nick` set) or full chat clear (`nick` = None).
    ClearChat {
        channel: String,
        nick: Option<String>,
        duration_secs: Option<u64>,
    },
    /// A single message deleted by a moderator.
    ClearMsg {
        channel: String,
        target_msgid: String,
        login: Option<String>,
        text: String,
    },
    /// Subscriptions, raids, announcements …; `system_msg` is Twitch's human-readable summary.
    UserNotice {
        channel: String,
        msg_id: String,
        system_msg: Option<String>,
        text: Option<String>,
        tags: Tags,
    },
    RoomState {
        channel: String,
        tags: Tags,
    },
    UserState {
        channel: Option<String>,
        tags: Tags,
    },
}

#[derive(Clone, Debug, PartialEq)]
pub enum Event {
    /// Informational text for the server buffer generated by the client itself.
    Status(String),
    /// Any server line without a more specific event, for display in the server buffer.
    ServerText {
        msg: Message,
    },
    /// RPL_WELCOME received.
    Registered {
        nick: String,
    },
    /// End of MOTD (or no MOTD): registration fully done, safe to run perform commands.
    Ready,
    ISupportChanged,
    CapsChanged {
        enabled: Vec<String>,
    },
    SaslResult {
        success: bool,
        message: String,
    },
    /// Server told us to reconnect (Twitch `RECONNECT`) or an STS upgrade is required.
    ReconnectRequested {
        tls_port: Option<u16>,
    },
    /// A persistent STS policy for this host (`duration` seconds; 0 = remove).
    StsPolicy {
        port: u16,
        duration: u64,
    },
    /// Server `ERROR` (normally precedes disconnect).
    Error {
        message: String,
    },
    NickChangedSelf {
        old: String,
        new: String,
    },
    Chat(Chat),
    CtcpRequest {
        from: Source,
        target: String,
        command: String,
        params: String,
    },
    CtcpReply {
        from: Source,
        command: String,
        params: String,
    },
    Join {
        channel: String,
        user: Source,
        account: Option<String>,
        realname: Option<String>,
        own: bool,
    },
    Part {
        channel: String,
        user: Source,
        reason: Option<String>,
        own: bool,
    },
    Kick {
        channel: String,
        by: Source,
        nick: String,
        reason: Option<String>,
        own: bool,
    },
    /// `channels` lists shared channels the user was in (empty for history lines).
    Quit {
        user: Source,
        reason: Option<String>,
        channels: Vec<String>,
        netsplit: bool,
    },
    Nick {
        old: String,
        new: String,
        channels: Vec<String>,
        own: bool,
    },
    Topic {
        channel: String,
        topic: String,
        by: Option<String>,
        changed: bool,
    },
    ChannelMode {
        channel: String,
        by: Option<Source>,
        changes: Vec<ModeChange>,
    },
    UserMode {
        changes: Vec<ModeChange>,
    },
    /// Channel member list or member prefixes changed.
    MembersChanged {
        channel: String,
    },
    /// Away/account/host/realname of a user changed.
    UserUpdated {
        nick: String,
    },
    Invite {
        by: Source,
        nick: String,
        channel: String,
    },
    Whois(WhoisInfo),
    ListEntry {
        channel: String,
        users: u32,
        topic: String,
    },
    ListEnd,
    /// Ban/except/invex list fetched with `MODE #chan b|e|I`.
    ModeList {
        channel: String,
        mode: char,
        entries: Vec<ModeListEntry>,
    },
    Names {
        channel: String,
        names: Vec<String>,
    },
    StandardReply {
        kind: StandardReplyKind,
        command: String,
        code: String,
        context: Vec<String>,
        description: String,
    },
    MonitorOnline {
        nicks: Vec<Source>,
    },
    MonitorOffline {
        nicks: Vec<String>,
    },
    Away {
        own: bool,
        message: Option<String>,
    },
    /// `draft/message-redaction`: a message was deleted.
    Redact {
        target: String,
        msgid: String,
        by: Source,
        reason: Option<String>,
    },
    /// `draft/read-marker`: the read position for `target` (timestamp, ms).
    ReadMarker {
        target: String,
        time: Option<i64>,
    },
    ChannelRename {
        old: String,
        new: String,
        reason: Option<String>,
    },
    /// A batch of history (`CHATHISTORY` or bouncer playback) for one target.
    History {
        target: String,
        events: Vec<SessionEvent>,
    },
    /// soju.im/bouncer-networks: network `id` added/changed (attributes) or removed (`None`).
    BouncerNetwork {
        id: String,
        attrs: Option<Vec<(String, String)>>,
    },
    Twitch(TwitchEvent),
}
